### ISSUE TITLE
program becomes unresponsive after trying to change the character

### ISSUE THREAD

**Issue by musicalskele** [ToadsworthLP/desktoptale#2]
### description of the issue: 
the program becomes unresponsive during and after changing the character, it can still move on it's own but it becomes almost impossible to control it or change it again. 
here's a recording of the issue :

https://github.com/ToadsworthLP/desktoptale/assets/36569350/4cfaaa99-7b5f-4c80-aeb5-52ad527083f3

### steps to reproduce the issue:

1.  run Desktoptale.exe
2. right click on the character

### environment:
operating system: windows 10

### system specs:
cpu: Intel i7-6700HQ
integrated gpu: Intel HD Graphics 530 
discrete gpu: Geforce GTX 960M
system memory: 16 GB

**Comment by ToadsworthLP** [comment]
Thank you for your bug report! This should be fixed as of #94bc071 but it the fix hasn't been properly released yet.
Does [this](https://cdn.discordapp.com/attachments/506580398386446348/1219020903812173954/Desktoptale-1.2.1-dev.zip?ex=6609c8af&is=65f753af&hm=48d7eba35f9331d718de5ed775897fc5192648f857093f18494525930a54bc53&) build fix it? 
It's built from that commit.

**Comment by musicalskele** [comment]
while the program isn't exactly crashing now it's definitely got issues
it acts fine until i try to change the character (or open the menu ig?) after i do that the character reacts to input in a really odd way, kinda hard to explain so maybe seeing this video would be more helpful

https://github.com/ToadsworthLP/desktoptale/assets/36569350/4deb57d7-726b-4bf6-8aa6-5e7698a8f24c

**Comment by ToadsworthLP** [comment]
I made some modification to how mouse events are handled in 1.3.0, does it still happen?

**Comment by musicalskele** [comment]
i apologize for the delayed response, i've been quite busy lately. as of version 1.3.1, the issue appears to be somewhat resolved. however, a similar problem to the one i recorded in the second video persists if you attempt to move your character immediately after right-clicking. 

interestingly, dragging the character with the left mouse button resolves the issue (if i recall correctly, this didn't help at all last time when i was playing around with it). so, it isn't as severe as the initial issue i encountered and remains fairly usable now honestly. the menu no longer behaves in a weird way and the program seems pretty stable when this issue happens. it's unlikely a person will attempt to move the character when they want to change the character or size so i think the issue is resolved. sorry if the response is a bit confusing it's 1 almost am for me rn.
