### ISSUE TITLE
Random Actions

### ISSUE THREAD

**Issue by 60lapie60** [ToadsworthLP/desktoptale#3]
I noticed that sometimes Clover will do their iconic dance as a random action. Is there a way for custom characters to also have custom random actions? If there isn't, could it be included in the next update? Maybe even have the choice to activate the custom action manually with the Z key.

**Comment by ToadsworthLP** [comment]
An action key to trigger a special animation with support for custom characters is on the roadmap, but not included in update 1.3.0.

**Comment by 60lapie60** [comment]
Could it also have the option to play a custom audio file when the animation plays, and have the animation have directional variations? Thanks.

**Comment by ToadsworthLP** [comment]
The action key to trigger a custom animation has been added in 1.6.0! Directional variations are supported, but sound has been omitted as an intentional design decision.
